# Generated by Django 4.1.13 on 2023-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('VehiculoId', models.AutoField(primary_key=True, serialize=False)),
                ('VehiculoNombre', models.CharField(max_length=50)),
            ],
        ),
    ]
