# Generated by Django 4.1.13 on 2023-11-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0002_remove_vehiculos_vehiculonombre_vehiculos_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
